# Training Configuration for 3D Gaussian Splatting

# Data Configuration
data:
  train_dir: "data/train"
  val_dir: "data/val"
  test_dir: "data/test"
  num_views: 4  # Number of input views
  image_size: [256, 256]
  batch_size: 4
  num_workers: 4

# Model Configuration
model:
  feature_dim: 256
  num_gaussians: 10000
  transformer_layers: 6
  num_heads: 8
  dropout: 0.1
  use_positional_encoding: true

# Training Configuration
training:
  epochs: 100
  learning_rate: 1e-4
  weight_decay: 1e-4
  scheduler_step_size: 30
  scheduler_gamma: 0.5
  gradient_clip: 1.0

# Loss Configuration
loss:
  reconstruction_weight: 1.0
  depth_weight: 0.1
  smoothness_weight: 0.01
  sparsity_weight: 0.001

# Rendering Configuration
rendering:
  near_plane: 0.1
  far_plane: 10.0
  fov: 60.0
  num_samples: 64

# Logging Configuration
logging:
  log_dir: "logs"
  save_freq: 10
  val_freq: 5
  tensorboard: true
  wandb: false

# Hardware Configuration
hardware:
  device: "cuda"  # or "cpu"
  mixed_precision: true
  num_gpus: 1
